In [1]:
# Import the dependencies
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head(50)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ushuaia,AR,2021-01-15 09:53:49,-54.8000,-68.3000,44.60,76,20,2.30
1,1,Lac Du Bonnet,CA,2021-01-15 09:53:49,50.2536,-96.0612,28.99,100,100,15.01
2,2,Esperance,AU,2021-01-15 09:53:49,-33.8667,121.9000,66.20,52,25,26.46
3,3,Lata,PT,2021-01-15 09:53:50,40.1629,-8.3327,46.99,100,90,1.14
4,4,Cidreira,BR,2021-01-15 09:52:48,-30.1811,-50.2056,74.10,83,68,17.56
5,5,Himare,AL,2021-01-15 09:53:50,40.1017,19.7447,52.00,50,0,2.30
6,6,Sudak,UA,2021-01-15 09:53:50,44.8500,34.9667,37.42,78,94,3.02
7,7,Puerto Ayora,EC,2021-01-15 09:53:50,-0.7393,-90.3518,72.00,95,76,1.01
8,8,Vestmannaeyjar,IS,2021-01-15 09:53:51,63.4427,-20.2734,42.80,81,75,23.02
9,9,Camacha,PT,2021-01-15 09:53:02,33.0833,-16.3333,57.20,58,40,11.50
10,10,New Norfolk,AU,2021-01-15 09:53:51,-42.7826,147.0587,55.99,66,96,1.01
11,11,Saint-Joseph,RE,2021-01-15 09:53:51,-21.3667,55.6167,84.20,70,75,19.57
12,12,Doume,CM,2021-01-15 09:53:52,4.2333,13.4500,94.60,22,100,1.97
13,13,Coxim,BR,2021-01-15 09:53:52,-18.5067,-54.7600,75.51,82,100,2.17
14,14,Hazorasp,UZ,2021-01-15 09:50:14,41.3194,61.0742,57.20,35,100,13.80
15,15,Dingle,PH,2021-01-15 09:53:52,10.9995,122.6711,78.03,90,8,8.10
16,16,Biloela,AU,2021-01-15 09:52:02,-24.4167,150.5000,75.97,64,0,10.16
17,17,Mataura,NZ,2021-01-15 09:52:44,-46.1927,168.8643,56.89,95,6,0.98
18,18,San Juan Bautista,PE,2021-01-15 09:53:53,-14.0108,-75.7358,66.20,82,0,6.91
19,19,Egvekinot,RU,2021-01-15 09:53:53,66.3167,-179.1667,-7.76,90,100,14.27
20,20,Rikitea,PF,2021-01-15 09:52:42,-23.1203,-134.9692,77.74,72,27,6.71
21,21,Bathsheba,BB,2021-01-15 09:52:45,13.2167,-59.5167,77.00,83,40,16.11
22,22,Kaitangata,NZ,2021-01-15 09:53:12,-46.2817,169.8464,56.39,96,19,3.47
23,23,Tokonou,GN,2021-01-15 09:53:54,9.6500,-9.7833,78.22,16,0,7.14
24,24,Suhbaatar,MN,2021-01-15 09:53:55,50.2314,106.2078,-7.98,86,27,5.59
25,25,Avarua,CK,2021-01-15 09:53:55,-21.2078,-159.7750,80.60,83,90,10.36
26,26,Paamiut,GL,2021-01-15 09:52:48,61.9940,-49.6678,24.84,88,100,13.09
27,27,Ilulissat,GL,2021-01-15 09:53:56,69.2167,-51.1000,17.60,73,90,12.66
28,28,Kayerkan,RU,2021-01-15 09:53:56,69.3497,87.7602,-40.54,79,23,2.26
29,29,Port Alfred,ZA,2021-01-15 09:53:56,-33.5906,26.8910,87.46,57,71,12.57
30,30,Khatanga,RU,2021-01-15 09:53:56,71.9667,102.5000,-50.84,75,14,1.28
31,31,Rabo De Peixe,PT,2021-01-15 09:53:57,37.8000,-25.5833,60.80,88,40,16.11
32,32,Walvis Bay,NaN,2021-01-15 09:53:57,-22.9575,14.5053,75.20,60,75,6.91
33,33,Bredasdorp,ZA,2021-01-15 09:52:45,-34.5322,20.0403,86.00,37,42,17.27
34,34,Port Elizabeth,ZA,2021-01-15 09:52:59,-33.9180,25.5701,73.40,83,0,16.11
35,35,Tiksi,RU,2021-01-15 09:53:58,71.6872,128.8694,-21.01,87,100,5.84
36,36,Thessalon,CA,2021-01-15 09:53:58,46.2501,-83.5666,35.60,80,90,5.75
37,37,Punta Arenas,CL,2021-01-15 09:53:58,-53.1500,-70.9167,50.00,87,90,9.22
38,38,Mount Isa,AU,2021-01-15 09:52:53,-20.7333,139.5000,98.60,18,0,8.05
39,39,Kaniama,CD,2021-01-15 09:53:58,-7.5667,24.1833,66.38,98,100,3.40
40,40,Manono,CD,2021-01-15 09:53:59,-7.3000,27.4167,69.85,93,100,1.03
41,41,Lara,AU,2021-01-15 09:53:59,-38.0167,144.4000,59.00,58,40,24.16
42,42,Biak,ID,2021-01-15 09:53:59,-0.9131,122.8766,80.38,79,97,5.75
43,43,Qaanaaq,GL,2021-01-15 09:52:40,77.4840,-69.3632,10.85,80,98,0.96
44,44,Torbay,CA,2021-01-15 09:53:59,47.6666,-52.7314,32.00,86,90,3.44
45,45,Jamestown,US,2021-01-15 09:52:46,42.0970,-79.2353,36.00,80,1,11.50
46,46,Thompson,CA,2021-01-15 09:50:17,55.7435,-97.8558,5.00,85,40,11.50
47,47,Georgetown,MY,2021-01-15 09:52:46,5.4112,100.3354,86.00,70,20,8.05
48,48,San Patricio,US,2021-01-15 09:53:20,28.0170,-97.5169,46.40,57,1,10.36
49,49,Tuktoyaktuk,CA,2021-01-15 09:52:48,69.4541,-133.0374,-19.70,88,18,11.10

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], \
                                dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 90

In [10]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Esperance,AU,2021-01-15 09:53:49,-33.8667,121.9000,66.20,52,25,26.46
4,4,Cidreira,BR,2021-01-15 09:52:48,-30.1811,-50.2056,74.10,83,68,17.56
5,5,Himare,AL,2021-01-15 09:53:50,40.1017,19.7447,52.00,50,0,2.30
7,7,Puerto Ayora,EC,2021-01-15 09:53:50,-0.7393,-90.3518,72.00,95,76,1.01
9,9,Camacha,PT,2021-01-15 09:53:02,33.0833,-16.3333,57.20,58,40,11.50
10,10,New Norfolk,AU,2021-01-15 09:53:51,-42.7826,147.0587,55.99,66,96,1.01
11,11,Saint-Joseph,RE,2021-01-15 09:53:51,-21.3667,55.6167,84.20,70,75,19.57
13,13,Coxim,BR,2021-01-15 09:53:52,-18.5067,-54.7600,75.51,82,100,2.17
14,14,Hazorasp,UZ,2021-01-15 09:50:14,41.3194,61.0742,57.20,35,100,13.80
15,15,Dingle,PH,2021-01-15 09:53:52,10.9995,122.6711,78.03,90,8,8.10

In [11]:
preferred_cities_df.count()

City_ID       327
City          327
Country       327
Date          327
Lat           327
Lng           327
Max Temp      327
Humidity      327
Cloudiness    327
Wind Speed    327
dtype: int64

In [12]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
2      Esperance      AU     66.20 -33.8667  121.9000
4       Cidreira      BR     74.10 -30.1811  -50.2056
5         Himare      AL     52.00  40.1017   19.7447
7   Puerto Ayora      EC     72.00  -0.7393  -90.3518
9        Camacha      PT     57.20  33.0833  -16.3333
10   New Norfolk      AU     55.99 -42.7826  147.0587
11  Saint-Joseph      RE     84.20 -21.3667   55.6167
13         Coxim      BR     75.51 -18.5067  -54.7600
14      Hazorasp      UZ     57.20  41.3194   61.0742
15        Dingle      PH     78.03  10.9995  122.6711

In [13]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [18]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [20]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Esperance,AU,66.20,-33.8667,121.9000,Hospitality Esperance
4,Cidreira,BR,74.10,-30.1811,-50.2056,Hotel Castelo
5,Himare,AL,52.00,40.1017,19.7447,Hotel Dhima
7,Puerto Ayora,EC,72.00,-0.7393,-90.3518,Castillo Galapagos
9,Camacha,PT,57.20,33.0833,-16.3333,Hotel Porto Santo & Spa
10,New Norfolk,AU,55.99,-42.7826,147.0587,The Shingles Riverside Cottages
11,Saint-Joseph,RE,84.20,-21.3667,55.6167,"""Plantation Bed and Breakfast"
13,Coxim,BR,75.51,-18.5067,-54.7600,Hotel Avenida
14,Hazorasp,UZ,57.20,41.3194,61.0742,Kemping wifi hotel
15,Dingle,PH,78.03,10.9995,122.6711,SEGAYA PROPERTY

In [23]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [27]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [28]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))